version: "3.9"

services:
  mongodb:
    image: mongo:4.2.11
    container_name: "mongodb"
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
  api:
    restart: always
    build: .
    container_name: "api"
    ports:
      - 8080:8080
    environment:
      PORT: :8080
      MGO_URI: "mongodb://mongodb:27017/chat"
    depends_on:
      - mongodb
